workflows:
  build-and-whitelabel:
    name: Build and White-label
    environment:
      flutter: stable
      APP_NAME: "MyApp"
      PACKAGE_NAME: "com.example.myapp"
      ANDROID_ICON_PATH: "path_to_android_icon.png"
      IOS_ICON_PATH: "path_to_ios_icon.png"
      THEME_COLOR: "#FF0000" # Replace with your desired theme color

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Change Android Package Name
        script: |
          sed -i '' "s/applicationId: 'com.example'/applicationId: '$PACKAGE_NAME'/" android/app/build.gradle
          sed -i '' "s/com.example/$PACKAGE_NAME/" android/app/src/main/AndroidManifest.xml

      - name: Change iOS Bundle Identifier
        script: flutter pub run flutter_launcher_name:main --bundle-identifier=$PACKAGE_NAME

      - name: Change Android App Icons
        script: cp $ANDROID_ICON_PATH android/app/src/main/res/mipmap/ic_launcher.png

      - name: Change iOS App Icons
        script: cp $IOS_ICON_PATH ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon.png

      - name: Change App Name
        script: |
          sed -i '' "s/android:label=\"OldAppName\"/android:label=\"$APP_NAME\"/" android/app/src/main/AndroidManifest.xml
          flutter pub run flutter_launcher_name:main --app-name=$APP_NAME

      - name: Apply Theme Color
        script: |
          # Use the THEME_COLOR variable in your code to dynamically set the theme color

      - name: Run tests
        script: flutter test
