# Project Configuration
project_name: "Your Whitelabeled App Name"
project_description: "A whitelabeled version of the original Flutter app"
project_organization: "Your Organization Name"

# App 1 Customization
app_1_id: "com.your.company.whitelabeled_app1"
app_1_display_name: "Your Whitelabeled App 1"
app_1_icon: "whitelabeled_icon1.png"
app_1_splash_screen: "whitelabeled_splash_screen1.png"

# Branding and Content Replacement for App 1
app_1_name: "Your Whitelabeled App 1 Name"
app_1_title: "Your Whitelabeled App 1 Title"
app_1_about_section: "Your whitelabeled app 1's about section"
app_1_contact_information: "Your whitelabeled app 1's contact information"
app_1_privacy_policy: "Your whitelabeled app 1's privacy policy"
app_1_terms_of_use: "Your whitelabeled app 1's terms of use"

# App 2 Customization
app_2_id: "com.your.company.whitelabeled_app2"
app_2_display_name: "Your Whitelabeled App 2"
app_2_icon: "whitelabeled_icon2.png"
app_2_splash_screen: "whitelabeled_splash_screen2.png"

# Branding and Content Replacement for App 2
app_2_name: "Your Whitelabeled App 2 Name"
app_2_title: "Your Whitelabeled App 2 Title"
app_2_about_section: "Your whitelabeled app 2's about section"
app_2_contact_information: "Your whitelabeled app 2's contact information"
app_2_privacy_policy: "Your whitelabeled app 2's privacy policy"
app_2_terms_of_use: "Your whitelabeled app 2's terms of use"

# Deployment Settings for App 1
app_1_app_store_connect_account: "YOUR_APP_STORE_CONNECT_ACCOUNT1"
app_1_google_play_console_account: "YOUR_GOOGLE_PLAY_CONSOLE_ACCOUNT1"

# Deployment Settings for App 2
app_2_app_store_connect_account: "YOUR_APP_STORE_CONNECT_ACCOUNT2"
app_2_google_play_console_account: "YOUR_GOOGLE_PLAY_CONSOLE_ACCOUNT2"
