workflows:
  hello-world:
    name: Hello world workflow
    scripts:
        - echo "Hello World!"
scripts:
  - name: Build for iOS         
    script: flutter build ios      
script: | 
    echo "android {  defaultConfig { applicationId '${PACKAGE_NAME}' }  }" > android/changePackage.gradle
    echo "apply from: rootProject.file('changePackage.gradle')" >> android/app/build.gradle