workflows:
  firstApp-workflow:
    name: First App Workflow
    environment:
      flutter: stable
     

    scripts:
      - name: Install dependencies for First App
        script: flutter pub get

      - name: Change Android Package Name for First App
        script: |
          sed -i '' "s/applicationId: 'com.example'/applicationId: '$PACKAGE_NAME_FIRST'/" android/app/build.gradle
          sed -i '' "s/com.example/$PACKAGE_NAME_FIRST/" android/app/src/main/AndroidManifest.xml

   

      - name: Change Android app name
        script: 
           sed -i.bak "s/android:label=.*/android:label="NAMENAME"/g" android/app/src/main/AndroidManifest.xml

      - name: Apply Theme Color for First App
        script: |
          # Use the THEME_COLOR_FIRST variable in your code to dynamically set the theme color for First App

      - name: Run tests for First App
        script: flutter test
      - name: Build APK
        script: flutter build apk --release --split-per-abi

  secondApp-workflow:
    name: Second App Workflow
    environment:
      flutter: stable
    

    scripts:
      - name: Install dependencies for Second App
        script: flutter pub get

      - name: Change Android Package Name for Second App
        script: |
          sed -i '' "s/applicationId: 'com.example'/applicationId: '$PACKAGE_NAME_SECOND'/" android/app/build.gradle
          sed -i '' "s/com.example/$PACKAGE_NAME_SECOND/" android/app/src/main/AndroidManifest.xml

      - name: Change App Name for Second App
        script: |
          sed -i '' "s/android:label=\"OldAppName\"/android:label=\"$APP_NAME_SECOND\"/" android/app/src/main/AndroidManifest.xml
          flutter pub run flutter_launcher_name:main --app-name=$APP_NAME_SECOND

      - name: Apply Theme Color for Second App
        script: |
          # Use the THEME_COLOR_SECOND variable in your code to dynamically set the theme color for Second App

      - name: Run tests for Second App
        script: flutter test
