workflows:
  firstApp-workflow:
    name: First App Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies for First App
        script: |
          flutter pub get
          flutter pub global activate rename; export PATH=“$PATH”:“$HOME/.pub-cache/bin”

      - name: Change name for First App
        script: |
         rename setAppName --targets ios,android --value "WLTest1";


      - name: Change package name for First App
        script: |       
         rename setBundleId --targets ios,android --value "com.zeepalm.welTestOne"

      - name: Apply Theme Color for First App
        script: |
          # Use the THEME_COLOR_FIRST variable in your code to dynamically set the theme color for First App  

          # for change assets   
      # - name: Get assets from Firebase Storage
      # # # gs://prac-of-whitelable.appspot.com/assets/drawable-hdpi/new_cartisan_logo.png
      #   script: |
      #    FILE_URL=$(curl --request GET --header "Authorization: Bearer 72178977a1de61eae95459251b2446873351bf04" "gs://prac-of-whitelable.appspot.com/assets.zip") | jq '.items[].downloadUrl' | xargs echo | cut -d '"' -f 2
      #    curl -H "Authorization: Bearer 72178977a1de61eae95459251b2446873351bf04" $FILE_URL --output assets.zip
      #   gsutil -m cp -r gs://prac-of-whitelable.appspot.com/assets.zip ./android/app/src/main/res

      - name: Get assets from Firebase Storage
        script: | 
          firebase login
          FILE_URL=$(curl --request GET --header "Authorization: Bearer 72178977a1de61eae95459251b2446873351bf04" "gs://prac-of-whitelable.appspot.com/assets.zip") | jq '.items[].downloadUrl' | xargs echo | cut -d '"' -f 2
         
      - name: Change Android icons
        script: cp -r ./$ASSETS_FOLDER/$ANDROID_ASSETS_FOLDER/* ./android/app/src/main/res

      - name: Run tests for First App
        script: flutter test

      - name: Build APK
        script: flutter build apk 
    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log

  secondApp-workflow:
    name: Second App Workflow
    environment:
      flutter: stable
    

    scripts:
      - name: Install dependencies for Second App
        script: flutter pub get

      - name: Change Android Package Name for Second App
        script: |
          sed -i '' "s/applicationId: 'com.example'/applicationId: '$PACKAGE_NAME_SECOND'/" android/app/build.gradle
          sed -i '' "s/com.example/$PACKAGE_NAME_SECOND/" android/app/src/main/AndroidManifest.xml

      - name: Change App Name for Second App
        script: |
          sed -i '' "s/android:label=\"OldAppName\"/android:label=\"$APP_NAME_SECOND\"/" android/app/src/main/AndroidManifest.xml
          flutter pub run flutter_launcher_name:main --app-name=$APP_NAME_SECOND

      - name: Apply Theme Color for Second App
        script: |
          # Use the THEME_COLOR_SECOND variable in your code to dynamically set the theme color for Second App

      - name: Run tests for Second App
        script: flutter test
